[package]
name = "rusty-store-inventory"
version = "0.1.0"
edition = "2021"

[dependencies]
# Authentication and security
bcrypt = "0.10.1"
uuid = { version = "1.3.3", features = ["v4"] }

# Serialization and data handling
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# CLI and input handling
clap = { version = "4.3.0", features = ["derive"] }

# Logging
log = "0.4"
env_logger = "0.10"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

[dev-dependencies]
# Testing dependencies
mockall = "0.11.3"
tempfile = "3.2"
```
